### ISSUE TITLE
Error : Repository Not Found

### ISSUE THREAD

**Issue by kmishal** [Brand-Boosting-GmbH/shopify-theme-preview#4]
@DavidPotato  I changed the version number  and add permission option in my action file
```
permissions:
  pull-requests: write 
```
Action is failing now

![image](https://github.com/Brand-Boosting-GmbH/shopify-theme-preview/assets/41513034/72c839f3-769b-48ec-ae77-47ffbfa4f183)

How can I resolve this issue?

**Comment by jds-tag** [comment]
I'm also having this issue on v1.2.1

**Comment by jds-tag** [comment]
@kmishal I was able to fix this by adding `contents: read` to the permissions section. You'll need this if your repo is private.

So your permissions block will be like:

```
permissions: 
  contents: read
  pull-requests: write
```

Now everything is working! I hope it helps!

FYI to maintainer I tried to PR this readme update against the repo but it wouldn't let me push.

**Comment by mc-0bit** [comment]
Added to example, thanks for reporting and sorry for the wait!
